name: 🪲 Bug Report
description: Help us improve ePlay!
title: "[BUG] "
labels: ":lady_beetle:  BUG"

body:
    - type: checkboxes
      id: profile
      attributes:
        label: 🦄 Select your Profile
        options:
          - label: Streamer
          - label: User
    - type: checkboxes
      id: device
      attributes:
        label: ⚙️ Device
        options:
          - label: Phone
          - label: Computer
    - type: dropdown
      id: os
      attributes:
        label: 💾 System
        options:
          - APPLE
          - ANDROID
          - WINDOWS
          - OTHER
    - type: dropdown
      id: browser
      attributes:
        label: 🖥️ Browser
        options:
          - label: CHROME
          - label: SAFARI
          - label: EDGE
          - label: FIREFOX
          - label: OTHER
    - type: dropdown
      id: section
      attributes:
        label: 📍 Where is the Bug?
        options:
          - 💬 LIVE CHATROOM 
          - 📺 CHANNEL 
          - 📡 STREAMING DASHBOARD
          - 👤 ACCOUNT
          - 🛒 BUY TOKENS
          - 🪙 TIPPING
          - 🔑 JOIN
          - 🔒 LOGIN
          - 💡 OTHER
    - type: input
      id: link
      attributes:
          label: 🔗 Which page is it? 
          description: Copy & Paste the Link URL here
          placeholder: https://
      validations:
          required: false
    - type: textarea
      id: description
      attributes:
          label: ℹ️ Description
          description: A clear and concise description of the problem
      validations:
          required: true
    - type: textarea
      id: how-to-reproduce
      attributes:
          label: 🧨 How to reproduce
          description: |
            ⚠️  This is the most important part of the report ⚠️ 
            Without a way to easily reproduce your issue, there is little chance we will be able to help you and work on a fix.
            Please, take the time to show us screenshots or/and a video that is needed for others to reproduce the problem.
          value: 
            1. Go to
            2. Then go to
      validations:
          required: true
    - type: textarea
      id: expected
      attributes:
          label: ⚡️ Expected Behavior
          description: |
            Optional: only if you have suggestions on a fix/reason for the bug
            Don't hesitate to create a pull request with your solution, it helps get faster feedback.
    - type: textarea
      id: additional-context
      attributes:
          label: 😇 Anything else you would like to add?
          description: "Optional: any other context about the problem: console log messages, screenshots, videos, etc."
